spring:
    data:
        mongodb:
            username: chat
            password: chat
            host: localhost
            port: 27017
            database: chat_app
            authentication-database: admin

server:
    port: 8088